services:
  - type: web
    name: ai-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    workingDir: backend
    autoDeploy: true
    envVars:
      - key: HF_TOKEN
        sync: false

  - type: web
    name: ai-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    workingDir: frontend
    autoDeploy: true
