services:
  - type: web
    name: ai-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    autoDeploy: true
    envVars:
      - key: HF_TOKEN
        sync: false

  - type: web
    name: ai-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    autoDeploy: true
